src/Entity/Country.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CountryRepository")
 */
class Country
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Stat", mappedBy="country", orphanRemoval=true)
     */
    private $stats;

    public function __construct()
    {
        $this->stats = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
    public function getContaminated(): ?int
    {
        $total=0;
        foreach ($this->getStats() as $stat) {
            $total += $stat->getContaminated();
        }
        return $total;
    }
    public function getHealed(): ?int
    {
        $total=0;
        foreach ($this->getStats() as $stat) {
            $total += $stat->getHealed();
        }
        return $total;
    }
    public function getZombified(): ?int
    {
        $total=0;
        foreach ($this->getStats() as $stat) {
            $total += $stat->getZombified();
        }
        return $total;
    }
    /**
     * @return Collection|Stat[]
     */
    public function getStats(): Collection
    {
        return $this->stats;
    }

    public function addStat(Stat $stat): self
    {
        if (!$this->stats->contains($stat)) {
            $this->stats[] = $stat;
            $stat->setCountry($this);
        }

        return $this;
    }

    public function removeStat(Stat $stat): self
    {
        if ($this->stats->contains($stat)) {
            $this->stats->removeElement($stat);
            // set the owning side to null (unless already changed)
            if ($stat->getCountry() === $this) {
                $stat->setCountry(null);
            }
        }

        return $this;
    }
}

templates/app/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Country index{% endblock %}

{% block body %}
    <h1>Country index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Pays</th>
                <th>Infecté</th>
                <th>Sauvé</th>
                <th>Zombifié</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for country in countries %}
            <tr class=" alert alert-{{ country.healed > country.zombified ? 'success' : 'danger' }} ">
                <td>{{ country.name }}</td>
                <td>{{ country.contaminated }}</td>
                <td>{{ country.healed }}</td>
                <td>{{ country.zombified }}</td>
                <td>
                    <a href="{{ path('country_show', {'id': country.id}) }}">show</a>
                    <a href="{{ path('country_edit', {'id': country.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('country_new') }}">Create new</a>
{% endblock %}