src/Entity/Stat.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\StatRepository")
 */
class Stat
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $contaminated;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $healed;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $zombified;

    /**
     * @ORM\Column(type="date")
     */
    private $stat_date;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Country", inversedBy="stats")
     * @ORM\JoinColumn(nullable=false)
     */
    private $country;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContaminated(): ?int
    {
        return $this->contaminated;
    }

    public function setContaminated(?int $contaminated): self
    {
        $this->contaminated = $contaminated;

        return $this;
    }

    public function getHealed(): ?int
    {
        return $this->healed;
    }

    public function setHealed(?int $healed): self
    {
        $this->healed = $healed;

        return $this;
    }

    public function getZombified(): ?int
    {
        return $this->zombified;
    }

    public function setZombified(?int $zombified): self
    {
        $this->zombified = $zombified;

        return $this;
    }

    public function getStatDate(): ?\DateTimeInterface
    {
        return $this->stat_date;
    }

    public function setStatDate(\DateTimeInterface $stat_date): self
    {
        $this->stat_date = $stat_date;

        return $this;
    }

    public function getCountry(): ?Country
    {
        return $this->country;
    }

    public function setCountry(?Country $country): self
    {
        $this->country = $country;

        return $this;
    }
}

src/Form/StatType.php
<?php

namespace App\Form;

use App\Entity\Country;
use App\Entity\Stat;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class StatType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('contaminated', NumberType::class)
            ->add('healed', NumberType::class)
            ->add('zombified', NumberType::class)
            ->add('stat_date', DateTimeType::class)
            ->add('country', EntityType::class, [
                'class' => Country::class,
                'choice_label' => 'name'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Stat::class,
        ]);
    }
}

src/Controller/StatController.php
<?php

namespace App\Controller;

use App\Entity\Stat;
use App\Form\StatType;
use App\Repository\StatRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/stat")
 */
class StatController extends AbstractController
{
    /**
     * @Route("/", name="stat_index", methods={"GET"})
     */
    public function index(StatRepository $statRepository): Response
    {
        return $this->render('stat/index.html.twig', [
            'stats' => $statRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="stat_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $stat = new Stat();
        $form = $this->createForm(StatType::class, $stat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($stat);
            $entityManager->flush();

            return $this->redirectToRoute('app_index');
        }

        return $this->render('stat/new.html.twig', [
            'stat' => $stat,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="stat_show", methods={"GET"})
     */
    public function show(Stat $stat): Response
    {
        return $this->render('stat/show.html.twig', [
            'stat' => $stat,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="stat_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Stat $stat): Response
    {
        $form = $this->createForm(StatType::class, $stat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('stat_index');
        }

        return $this->render('stat/edit.html.twig', [
            'stat' => $stat,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="stat_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Stat $stat): Response
    {
        if ($this->isCsrfTokenValid('delete'.$stat->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($stat);
            $entityManager->flush();
        }

        return $this->redirectToRoute('stat_index');
    }
}

templates/stat/_delete_form.html.twig
<form method="post" action="{{ path('stat_delete', {'id': stat.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ stat.id) }}">
    <button class="btn">Delete</button>
</form>

templates/stat/_form.html.twig
<div class="container mt-3">
    <div class="row">
        <div class="col">

            {{ form_start(form) }}
            {{ form_widget(form) }}
                <button class="btn btn-success">Ajouter une stat</button>
            {{ form_end(form) }}

        </div>
    </div>
</div>

templates/stat/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Stat{% endblock %}

{% block body %}
    <h1>Edit Stat</h1>

    {{ include('stat/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('stat_index') }}">back to list</a>

    {{ include('stat/_delete_form.html.twig') }}
{% endblock %}

templates/stat/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Stat index{% endblock %}

{% block body %}
    <h1>Stat index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Pays</th>
                <th>Contaminé</th>
                <th>Soigné</th>
                <th>Zombifié</th>
                <th>Stat_date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for stat in stats %}
            <tr class=" alert alert-{{ stat.healed > stat.zombified ? 'success' : 'danger' }} ">
                <td>{{ stat.id }}</td>
                <td>{{ stat.country.name }}</td>
                <td>{{ stat.contaminated }}</td>
                <td>{{ stat.healed }}</td>
                <td>{{ stat.zombified }}</td>
                <td>{{ stat.statDate ? stat.statDate|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('stat_show', {'id': stat.id}) }}">show</a>
                    <a href="{{ path('stat_edit', {'id': stat.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('stat_new') }}">Create new</a>
{% endblock %}

templates/stat/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Stat{% endblock %}

{% block body %}
    <h1>Create new Stat</h1>

    {{ include('stat/_form.html.twig') }}

    <a href="{{ path('stat_index') }}">back to list</a>
{% endblock %}

templates/stat/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Stat{% endblock %}

{% block body %}
    <h1>Stat</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ stat.id }}</td>
            </tr>
            <tr>
                <th>Pays</th>
                <td>{{ stat.country.name }}</td>
            </tr>
            <tr>
                <th>Contaminé</th>
                <td>{{ stat.contaminated }}</td>
            </tr>
            <tr>
                <th>Soigné</th>
                <td>{{ stat.healed }}</td>
            </tr>
            <tr>
                <th>Zombifié</th>
                <td>{{ stat.zombified }}</td>
            </tr>

            <tr>
                <th>Stat_date</th>
                <td>{{ stat.statDate ? stat.statDate|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('stat_index') }}">back to list</a>

    <a href="{{ path('stat_edit', {'id': stat.id}) }}">edit</a>

    {{ include('stat/_delete_form.html.twig') }}
{% endblock %}